### ISSUE TITLE
Build Dependencies

### ISSUE THREAD

**Issue by ediabal** [petermikitsh/stencil-monorepo#1]
Hey, saw this project and I'm doing basically the exact same thing and running into the same issues you look to be running into here. Have you been able to figure out how to get your build dependencies / build order to work? I find that you have to build twice just to get the thing to serve due to one component not being built yet that the other depends on.

**Comment by petermikitsh** [comment]
I'm assuming your monorepo project has one subpackage, that's your stencil components, and another subpackage, that might be a web application where you're consuming them. To build successfully, you'll need stencil components built prior to building your web app. If not, this contrived example should still suffice for discuss build order issues.

Assume each subpackage implements the following commands in `package.json`:

| Command | Description                                                 |
|---------|-------------------------------------------------------------|
| `clean` | Remove any build artifacts                                  |
| `build` | Create production-grade build artifacts                     |
| `start` | Create development-grade build artifacts (w/ file watchers) |



If you're using lerna, you might want to run `lerna run build` from the project root, which will run the 'build' command in each subpackage, order not guaranteed.

What I've seen in some projects is the addition of a `scripts` folder, and you could put a shell-script like `scripts/build.sh` in there.

Then your package.json would be:

```json
{
  "scripts": {
    "build": "./scripts/build.sh"
  }
}
```

And you could have custom logic for handling build order in there. Let's say Project X must be built before Project Y. You could use Lerna's [scope flag](https://www.npmjs.com/package/@lerna/filter-options) to control the build order.

```sh
# scripts/build.sh
lerna run clean # delete all build artifacts
lerna run build --scope @scope/project-x # Build X first
lerna run build --scope @scope/project-y # Build Y second
```

Lastly, to kick off your build process, since everything is now abstracted simply, just run:

```
npm run build
```

**Comment by ediabal** [comment]
Thanks @petermikitsh! This is exactly what I though but the bash script is a good idea.

**Comment by mdings** [comment]
So I'm a bit late to the party but I'm trying to understand how this might help my development cycle.

Does this mean that whenever I make change to project-a, I have to first rebuild it to see the updates in project-b? I did a checkout of your repo and whenever I make changes to project-a, they are immediately reloaded in project-a, although not in project-b (which consumer project-a). Is this at-all possible?

**Comment by ediabal** [comment]
@mdings that is correct.

If a change happens in project-a and it is rebuilt it does not trigger a rebuild of project-b that consumes it. You can think of it like project-b is built with project-a inside it and is not actively watching for changes on project-a, just itself. There may be a workaround to this but I'm not finding it affecting my project too much. Honestly, this exposed a structure change that we probably should have made to have projects like project-a and project-b live in the same project/workspace when they are so interconnected.

I understand that the last sentence above may not be ideal for most circumstances but in our case now separate projects are really being all built and watched at the same time in parallel. You're usually just working on one project and just using a finished build of the other.
